import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import SocketProvider from "@/context/useSocket";
import { QRCodeProvider } from "@/context/useQrcode";
import clsx from "clsx";
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });
const poppins = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx("bg-gray-900 relative", poppins.className)} >
        <StoreProvider>
          <SocketProvider url="https://socket-io-chat-backend.onrender.com">
            <QRCodeProvider>{children}</QRCodeProvider>
          </SocketProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
